# Koneksi ke listener tunnel (di VPS)
tunnel_addr: "tunnel.kristiawan.my.id:9443"
skip_tls_verify: true

# JWT Auth (harus cocok dengan server)
jwt_secret: "supersecretjwtkey"
jwt_issuer: "mytunnel"
jwt_expire_sec: 3600

# Mapping host -> target lokal
tunnels:
  - hostname: "web.kristiawan.my.id"
    target: "127.0.0.1:8087"
    mode: "http"
